name: first
description: "A new Flutter project."

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  firebase_messaging: ^14.9.1
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.6.1
  location: ^6.0.1
  google_maps_utils: 2.0.0+1
  http: ^1.2.1
  cloud_firestore: ^4.17.2
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  firebase_storage: ^11.7.0
  provider: ^6.1.2
  pinput: ^4.0.0
  shared_preferences: ^2.2.2
  google_generative_ai: ^0.2.2
  intl: ^0.19.0
  flutter_slidable: ^3.1.0
  image_picker: ^1.0.7
  flutter_svg: ^2.0.10+1
  google_nav_bar: ^5.0.6  
  line_icons: ^2.0.3
  fluttertoast: ^8.2.4
  flutter_google_maps_webservices: ^1.1.1
  razorpay_flutter: ^1.3.6
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0



flutter:

  
  uses-material-design: true
  assets:
  - assets/bike.svg
  - assets/car.svg
  - assets/tow.svg
  - assets/6wheel.svg
  - assets/logo.jpeg
  - assets/Logo .svg
  - assets/message.svg

  